name: smart_car
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Machine learning
  ml_algo: ^16.18.0
  ml_dataframe: ^1.6.0
  ml_preprocessing: ^7.0.2

  # Bluetooth
  flutter_bluetooth_classic_serial: ^1.3.2

  # Charts
  fl_chart: ^1.2.0
  chart_sparkline: ^1.1.2

  # Logging
  flutter_logs: ^2.2.1

  # GPS
  location: ^8.0.1
  haversine_distance: ^1.2.1

  # Bloc
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

  # Mailer
  flutter_mailer: ^3.0.1

  # Sensors
  sensors_plus: ^7.0.0

  # Storage
  shared_preferences: ^2.5.0

  # Json annotation
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0

  # Path provider
  path_provider: ^2.1.5

  # Foreground service
  flutter_foreground_task: ^9.2.1
  flutter_background: ^1.3.1

  # Toast
  fluttertoast: ^9.0.0
  another_flushbar: ^1.12.32

  # Icons
  line_icons: ^2.0.3
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.8

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  xml: ^6.6.1
  http: ^1.6.0

  # intl
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0

  # Uuid
  uuid: ^4.5.3

  # Timeago
  timeago: ^3.7.1
  csv: ^5.1.1

  # Share
  share_plus: ^12.0.1

  # File picker
  file_picker: ^10.3.10

  # Sentry
  sentry_flutter: ^9.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/csv/
    - assets/models/
