name: smart_car
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth
  flutter_bluetooth_serial: ^0.4.0

  # Charts
  fl_chart: ^0.45.0
  charts_painter: ^2.0.0
  chart_sparkline: ^1.0.7

  # Logging
  flutter_logs: ^2.1.4

  # GPS
  geolocator: ^8.2.0

  # Bloc
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  # Mailer
  flutter_mailer: ^2.0.1

  # Sensors
  sensors: ^2.0.3
  environment_sensors: ^0.2.0
  flutter_sensors: ^1.0.1

  # Storage
  shared_preferences: ^2.0.11

  # Json annotation
  json_annotation: ^4.4.0

  # Path provider
  path_provider: ^2.0.8

  # Foreground service
  flutter_foreground_task: ^3.5.5
  flutter_background: ^1.1.0

  # Toast
  fluttertoast: ^8.0.8
  fl_toast: ^3.1.0
  another_flushbar: ^1.10.28 

  # Icons
  line_icons: ^2.0.1
  ionicons: ^0.1.2
  cupertino_icons: ^1.0.2

  # Maps
  flutter_map: ^0.14.0

  #intl
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  build_runner:
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/
